import './commons/glide.min.js'
import './commons/nouislider.min.js'
import './commons/imports.js'
import './layout/layout.js'
// import './pages/home.js'
// import './pages/mis-lucas.js'
// import './pages/products.js'